version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template samTemplate.yml --s3-bucket arficatbucket --output yml > outputSamTemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputSamTemplate.yml
